from typing import Literal

# OrderStatusType = Literal[
#     "Shipped ovrnigh",
#     "SHP Await Invoice",
#     "DS-Entry hold",
#     "DS-Pending Inv Error",
#     "DS-SHP Pend Cust Inv",
#     "DS-Credit Review",
#     "DS-SHP Await Invoice",
#     "DS-Await Vend SHP",
#     "C.C. Shipped",
#     "Awaiting wave",
#     "DS-PO Gen Pending",
#     "Invoiced",
#     "Awaiting stock",
#     "Process pending",
#     "Shipped",
#     "Entry hold",
#     "Shipper printed",
#     "DS-C.C. Shipped",
#     "Pricing Hold",
#     "Credit Review",
#     "Ready to Print"
# ]

DeliveryStatusType = Literal[
    "On-Time",
    "Late Delivery",
    "Early Delivery",
    "No POD"
]

status_map = {
    "Carton Reprint": "Order being processed",
    "Auto divert scanned": "Order being processed",
    "Check-Pack Bypass Divert": "Order being processed",
    "Scanned by overhead scanner": "Order being processed",
    "Scanned Manually": "Order being processed",
    "Scan to truck": "Order being processed",
    "Scan to pallet (staging)": "Order being processed",
    "Scan from": "Order Shipped",
    "Transfer from truck XXXX to location XXXX": "Order being processed",
    "Transfer to staging location": "Order being processed",
    "Confirmed on Truck": "Order Shipped",
    "Picked up by courier": "Order shipped",
    "On delivery with courier.": "Order shipped",
    "Delivered by courier.": "Delivered",
    "Delivered by truck xxxx/Route xxxx Signed for by:": "Delivered",
    "Undelivered by truck xxxx/Route xxxx Reason:": "Failed Delivery",
    "Unplan Delivery": "Delivered",
    "Express Return": "Picked Up",
    "Picked Up": "Picked Up",
    "Shipping Notice Received": "Order Being Processed",
    "Pickup Requested": "Pickup Requested",
    "Scanned for courier delivery.": "Scanned for courier delivery",
    "Entry hold": "Order being processed",
    "Cancelled": "Cancelled",
    "Credit Review": "Order being processed",
    "Invoiced": "Invoiced",
    "Shipped": "Order Shipped",
    "Shipper printed": "Order being processed",
    "Acknowledged": "Order being processed",
    "Picked": "Order being processed",
    "Pricing Hold": "Order being processed",
    "Rec'd complete": "Order being processed",
    "Process pending": "Order being processed",
    "Manual Hold": "Order being processed",
    "C.C. Shipped": "Order Shipped",
    "Furniture Hold": "Order being processed",
    "Short ship hold": "Order being processed",
    "Awaiting stock": "Order being processed",
    "Partial receipt": "Partial receipt",
    "In-transit": "Order Shipped",
    "DS-Credit Review": "Order being processed",
    "DS-Entry hold": "Order being processed",
    "DS-Pricing Hold": "Order being processed",
    "DS-SHP Pend Cust inv": "Order being processed",
    "DS-Cancelled": "Cancelled",
    "DS-Invoiced": "Invoiced",
    "DS-Manual Hold": "Order being processed",
    "DS-C.C. Shipped": "Order Shipped",
    "DS-Sht Shp Hld": "Order being processed",
    "DS-Awaiting Stk": "Order being processed",
    "Shipped ovrnigh": "Order Shipped",
    "Awaiting wave": "Order being processed",
    "Ready to Print": "Order being processed",
    "Address Hold": "Address prob. pls. call",
    "Delivery confirmed by audit": "Delivered",
    "Pickup Printed": "Pickup requested",
    "Manifested": "Pickup scheduled",
    "Failed Pick up": "Failed Pick up",
    "Cancelled": "Pickup cancelled",
    "Picked Up": "Picked Up",
    "Ready for re-manifesting": "Pickup Requested",
    "SHP Await Invoice": "Order Shipped",
    "DS-SHP Await Invoice": "Order Shipped",
    "Credit Review": "Credit card being declined",
    "DS-Credit Review": "Credit card being declined"
}
